### ISSUE TITLE
forum thread? 

### ISSUE THREAD

**Issue by 321nick** [pardeike/CameraPlus#1]
does htis mod have a forum thread? steam workshop page?

**Comment by pardeike** [comment]
Not yet. I will create one and put the mod on steam workshop too.

**Comment by jptagman** [comment]
issue with item numbers/names not showing up

numbers for everything and names dont show until you zoom WAY in

the pawn names show up perfectly!!!!

other than that awesome!!!!

**Comment by jptagman** [comment]
can you add a GUI interface of enabling/disabling this mod
and GUI interface of when to show item counts when zooming
and GUI interface of enabling/disabling of having it pause at zooming in OR pressing a button to hold and zoom in further? iduno just ideas...

**Comment by pardeike** [comment]
Forum thread created so I can close this Issue. @jptagman please create a separate Issue instead of commenting on non-related issues (and add more details or screenshots). Thank you.
