### ISSUE TITLE
[FEATURE REQUEST] Changable panning speed with keyboard

### ISSUE THREAD

**Issue by rimpy-custom** [pardeike/CameraPlus#10]
Pardeike, thank you for this. May I ask for an option to change panning speed when using keyaboard button. Vanilla panning speed settings (WASD buttons) looks good, but with Camera+ on middle zoom camera moves too fast for my preference. I want to change that but cannot find settings for that.

**Comment by pardeike** [comment]
There are a panning speed settings. You have two: one for close up and one for zoomed out. Do they allow you to set what you want and if not, what’s your suggestion?
