### ISSUE TITLE
Suggestion: For Zoom settings, replace Near with ZoomedInPercent and Far with ZoomedOutPercent

### ISSUE THREAD

**Issue by Ragnar-F** [pardeike/CameraPlus#17]
In mod settings -> the first 2 sliders for "Zoom", I recommend replacing "Near" (Near) with "Maximum zoomed in factor" (ZoomedInPercent) and "Far" (Far) with "Maximum zoomed out factor" (ZoomedOutPercent). They are more accurate and easier to understand.

![image](https://user-images.githubusercontent.com/1332321/150561900-660da0f8-405c-4791-800b-0fcc671a2c2c.png)

Currently, ZoomedInPercent and ZoomedOutPercent are not used in the code.

**Comment by pardeike** [comment]
fixed in next release
