### ISSUE TITLE
Some texts are not translatable

### ISSUE THREAD

**Issue by Ragnar-F** [pardeike/CameraPlus#18]
![image](https://user-images.githubusercontent.com/1332321/150563151-a7dc72cc-8720-4405-a3f0-5be08fa9e250.png)

For both, there are already keys and therefore potential translations:

- "Off" in Core\Language\English\Keyed\Misc_Gameplay.xml
- "None" in Core\Language\English\Keyed\ITabs.xml

Roughly speaking, just appending `.Translate()` should be enough - new keys are not necessary.

**Comment by pardeike** [comment]
will be fixed in next release
