### ISSUE TITLE
Error with the latest unstable build

### ISSUE THREAD

**Issue by NoirFry** [pardeike/CameraPlus#20]
Starting with 1.3.3298
On startup:
`
Error in static constructor of CrossPromotionModule.CrossPromotion: System.TypeLoadException: Could not load type of field 'CrossPromotionModule.CrossPromotion:promotionMods' (2) due to: Could not resolve type with token 0100001a (from typeref, class/assembly Steamworks.SteamUGCDetails_t, Assembly-CSharp-firstpass, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null) assembly:Assembly-CSharp-firstpass, Version=0.0.0.0, Culture=neutral, PublicKeyToken=null type:Steamworks.SteamUGCDetails_t member:(null) signature:<none>
  at (wrapper managed-to-native) System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor(intptr)
  at System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor (System.RuntimeTypeHandle type) [0x0002a] in <eae584ce26bc40229c1b1aa476bfa589>:0 
  at Verse.StaticConstructorOnStartupUtility.CallAll () [0x0001a] in <a1e11ddd5c5946b69a21b6e7ae6fd8b6>:0  
(Filename: C:\buildslave\unity\build\Runtime/Export/Debug/Debug.bindings.h Line: 39)
`

`
Exception getting types in assembly CameraPlus, Version=2.2.3.0, Culture=neutral, PublicKeyToken=null
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.GenTypes/<get_AllTypes>d__4:MoveNext ()
Verse.StaticConstructorOnStartupUtility:ReportProbablyMissingAttributes ()
Verse.PlayDataLoader/<>c:<DoPlayLoad>b__4_3 ()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished ()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent ()
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Entry:Update ()
`

On save load:
`Exception getting types in assembly CameraPlus, Version=2.2.3.0, Culture=neutral, PublicKeyToken=null
UnityEngine.StackTraceUtility:ExtractStackTrace ()
Verse.Log:Error (string)
Verse.GenTypes/<get_AllTypes>d__4:MoveNext ()
System.Linq.Enumerable/WhereEnumerableIterator`1<System.Type>:ToList ()
System.Linq.Enumerable:ToList<System.Type> (System.Collections.Generic.IEnumerable`1<System.Type>)
Verse.GenTypes:AllSubclassesNonAbstract (System.Type)
Verse.Section:.ctor (Verse.IntVec3,Verse.Map)
Verse.MapDrawer:RegenerateEverythingNow ()
Verse.Map:<FinalizeInit>b__143_0 ()
Verse.LongEventHandler:ExecuteToExecuteWhenFinished ()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent ()
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
Verse.Root_Play:Update ()
`

**Comment by pardeike** [comment]
Most likely a corrupt Steam download of the Camera+ mod. I test my mods with the latest versions all the time.

**Comment by NoirFry** [comment]
I resubscribed but it didn't help.

I think, there are some changes starting with unstable 1.3.3298, example:
[this line](https://github.com/pardeike/CameraPlus/blob/a0f8187ab8a2f2867488cdefaf86fefe180bfa71/Source/CrossPromotion.cs#L252)
but `WorkshopItemHook.steamAuthor` is now private

**Comment by NoirFry** [comment]
My previous comment is unrelated i guess. Access modifies have changed some time ago and as the mod is linked against a Nuget package with public members it works with private too.

I isolated the problem to this:
https://gist.github.com/NoirFry/1caa2d55ea0fe60d7f70c89b43d6deee
with minimal mods i still get 2 errors on startup.
Recompiling this mod without `CrossPromoion` let the game start with no errors.

Edit: updated the first message to include that error too

**Comment by pardeike** [comment]
I have not yet adapted all my mods to the latest beta. Stay tuned.

**Comment by pardeike** [comment]
Fixed
