### ISSUE TITLE
"Cannot find field Stdfld rootSize in CameraDriver.Update"

### ISSUE THREAD

**Issue by Genaeve** [pardeike/CameraPlus#24]
I think the following error has to do with your mod. Fyi I haven't had any issues, it just shows up as a red error in my log. 
[CameraDriver.txt](https://github.com/pardeike/CameraPlus/files/8627442/CameraDriver.txt)

**Comment by pardeike** [comment]
It’s a mod conflict. TD Enhancements or some other mod modifies the camera driver and you cannot have two mods take control over it at the same time.

**Comment by Genaeve** [comment]
Gotcha! Thank you for answering! <3
