### ISSUE TITLE
Black Screen

### ISSUE THREAD

**Issue by pardeike** [pardeike/CameraPlus#26]
When loading only Camera+ and Harmony, I get a blackscreen.

-- submitted by dark.shadow4@web.de

**Comment by DarkShadow44** [comment]
That's me, if you need more info, please tell me. I'm not 100% sure  if your mod is really at fault here. I added Camera+ to a 100 other mods and then I don't get a blackscreen...

**Comment by pardeike** [comment]
That’s definitely not an issue that Harmony or Camera+ have. Please reinstall both and/or RimWorld. Most common problem are corrupt Steam downloads. I get those kind of reports like 2x a week. Never is it my problem.

**Comment by DarkShadow44** [comment]
Thank you and sorry for bothering!
