### ISSUE TITLE
GOOGLED to get here.

### ISSUE THREAD

**Issue by jptagman** [pardeike/CameraPlus#3]
maybe change the name to UNLIMITED ZOOM or ZOOM infinity or something instead of CAMERA+, just because to find this i tried google'ing several words that would unrestrict the zooming view. i had to read 2 forums to come across a suggestion of this camera+ mod name. IN all if you keep camera+ it will become recognized and more commonly known so it is AWESOME!

**Comment by pardeike** [comment]
Thanks for your suggestion, but I will not change the name. It's just a toy mod to show how Harmony works. Anyway, cool that you like it!
