### ISSUE TITLE
Breaks snapping to colonists since update on 9nov

### ISSUE THREAD

**Issue by rhmkrutov** [pardeike/CameraPlus#30]
Hi
Using steam version updated 9 nov 2022, I can not snap to colonists using double click or "jump to location" function anymore.

Disabling C+ mod in my modlist helps with this. 

I can't provide any logs, as there is nothing in dev log when I double click colonists or use "jump" function from events.

**Comment by pardeike** [comment]
Known problem, I forgot to commit my last changes and had a new computer. As a result the changes got lost when I added new code yesterday. Need to get my laptop tonight that still has the uncommitted changes that fixed this problem previously. 

I keep this issue up to avoid duplicates
