### ISSUE TITLE
Hide silouhettes on progress renderer screenshots

### ISSUE THREAD

**Issue by Oculyn** [pardeike/CameraPlus#33]
Currently, the silouhettes show on screenshots taken by progress renderer. This makes detail shots a lot less appealing since you can't see the pawns, but only the silouhette. Vanilla's markers are not shown on progress renderer, for reference: 
Ingame scrrenshot from far away of Thrumbos that I have disabled camera+ silouhettes for: ![image](https://github.com/pardeike/CameraPlus/assets/16278744/c3de6c88-6ec5-423a-9f48-5f4942892771)
Those same thrumbos on the progress renderer image: 
![image](https://github.com/pardeike/CameraPlus/assets/16278744/c53f97fa-536a-4001-990c-69c0bdb650ab)
Pawns on the progress renderer image: 
![image](https://github.com/pardeike/CameraPlus/assets/16278744/0d0f5e9b-80d2-4b59-adaa-27df1136580d)

**Comment by pardeike** [comment]
Camera+ has a flag that turns off everything so if ProgressRenderer sets it before and resets it after its snapshot it will solve the problem. 

https://github.com/pardeike/CameraPlus/blob/a65c18b775dccf8d5d9e44f1e7e193460d49aaef/Source/Main.cs#L22

**Comment by JonathanTroyer** [comment]
This will be done in Progress Renderer, so this issue can be closed.
