### ISSUE TITLE
ZOOM ITEM NAME NOT SHOWING UNTIL ZOOMED WAY IN issue not error

### ISSUE THREAD

**Issue by jptagman** [pardeike/CameraPlus#4]
issue with item numbers/names not showing up
ATTACHED 2 PHOTOS
http://imgur.com/a/cjgYS

numbers for everything and names don't show until you zoom WAY in
it is like the normal zoom settings to show names is now set at the lowest limit somehow default.
but the pawn names show up perfectly!!!! probably because they don't hide when zooming out.

BEGGING:
  Awesome Mod!!!! 
  i need this i have a tiny screen and its hard to see stuff and REALLY FUN TO ZOOM IN!!!!!!
  PLEASE PLEASE PLEASE PPLLEEEAASSEEE fix the issue!!! pretty please!!!

PS: can you add a GUI interface of enabling/disabling this mod

**Comment by pardeike** [comment]
Labels fixed in v1.0.1
